# fly.toml app configuration file generated for covercraft-convert on 2025-08-13T13:04:18-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'covercraft-convert'
primary_region = 'den'

[build]

[[mounts]]
  source = 'tmp'
  destination = '/pdf/tmp'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
